#!/usr/bin/env bash
set -euo pipefail

export LLM_ENABLED="${AGENT_LLM_ENABLED:-1}"
export LLM_QUERY_PLAN_ENABLED="${AGENT_LLM_QUERY_PLAN_ENABLED:-0}"
export LLM_POLISH_ENABLED="${AGENT_LLM_POLISH_ENABLED:-1}"
export LLM_VERIFY_ENABLED="${AGENT_LLM_VERIFY_ENABLED:-0}"
export LLM_TEMPERATURE="${AGENT_LLM_TEMPERATURE:-0}"
export LLM_MAX_TOKENS="${AGENT_LLM_MAX_TOKENS:-384}"
export LLM_EVIDENCE_CHAR_BUDGET="${AGENT_LLM_EVIDENCE_CHAR_BUDGET:-1400}"
export DENSE_ENABLED="${AGENT_DENSE_ENABLED:-0}"
export RERANK_ENABLED="${AGENT_RERANK_ENABLED:-0}"

python3 scripts/diagnose_queries.py "$@"
