#!/usr/bin/env bash
set -euo pipefail

export LLM_ENABLED="${AGENT_LLM_ENABLED:-0}"
export LLM_QUERY_PLAN_ENABLED="${AGENT_LLM_QUERY_PLAN_ENABLED:-0}"
export LLM_QUERY_PLANNER_ENABLED="${AGENT_LLM_QUERY_PLANNER_ENABLED:-0}"
export LLM_POLISH_ENABLED="${AGENT_LLM_POLISH_ENABLED:-0}"
export LLM_VERIFY_ENABLED="${AGENT_LLM_VERIFY_ENABLED:-0}"
export LLM_FINAL_GENERATION_ENABLED="${AGENT_LLM_FINAL_GENERATION_ENABLED:-0}"
export DENSE_ENABLED="${AGENT_DENSE_ENABLED:-0}"
export RERANK_ENABLED="${AGENT_RERANK_ENABLED:-1}"
export RERANK_BASE_URL="${AGENT_RERANK_BASE_URL:-http://127.0.0.1:8003/v1}"
export RERANK_MODEL="${AGENT_RERANK_MODEL:-bge-reranker-v2-m3}"
export RERANK_API_KEY="${AGENT_RERANK_API_KEY:-EMPTY}"
export RERANK_TIMEOUT_SECONDS="${AGENT_RERANK_TIMEOUT_SECONDS:-45}"
export RERANK_TOP_N="${AGENT_RERANK_TOP_N:-15}"
export RERANK_MAX_CANDIDATES="${AGENT_RERANK_MAX_CANDIDATES:-24}"
export RERANK_FORCE="${AGENT_RERANK_FORCE:-1}"

python3 scripts/evaluate.py "$@"
